config/routes.rb
Rottenpotatoes::Application.routes.draw do
  resources :users do
  end

  match '/myProfile', to: 'users#myProfile', as: 'myProfile', via: :get

  get 'login', to: 'sessions#new', as: 'sign_up'
  post 'login', to: 'sessions#create', as: 'log_in'
  get 'welcome', to: 'sessions#welcome', as: "login_signup"
  get 'authorized', to: 'sessions#page_requires_login'
  get 'logout', to: 'sessions#logout', as: 'logout'

  resources :events do
    resources :comments
  end 
  
  # map '/' to be a redirect to '/events'
  root :to => redirect('/welcome')

  match '/search_result', to: 'events#index', as: 'search_result', via: :get
  match '/join', to: 'events#join', as: 'join', via: :get
  match '/events/:id/promote', to: 'events#promote', as: 'promote', via: :get
  match '/events/:id/ratePeople', to: 'events#ratePeople', as: 'rate', via: :get
  match '/events/:id/rateUser', to: 'users#rateUser', as: 'rate_user', via: :put

  match '/events/:event_id/comments/:id/react/:action_id', to: 'comments#react', as: 'react', via: :put

  get '/auth/:provider/callback' => 'sessions#omniauth', as: 'oauth'
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    has_many :comments, :dependent => :destroy
    has_many :reactions, :dependent => :destroy
    has_and_belongs_to_many :events

    def self.from_omniauth(auth)
        where(email: auth.info.email).first_or_initialize do |user|
          user.username = auth.info.name
          user.email = auth.info.email
          user.password = SecureRandom.hex
        end
    end
    def promote_event
      if self.coins >= 10
        update_attribute(:coins, self.coins - 10)
        return true
      end
      return false
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    if cannot_create_user?(user_params)
      flash[:warning] = 'fields cannot be empty'
      redirect_to '/users/new?' and return
    end
    if User.find_by(username: user_params["username"])
      flash[:warning] = "username already exists"
      redirect_to '/users/new?' and return
    end
    @user = User.create(user_params)
    @user.update_attributes!({:rating => 5, :num_rating_got => 1})
    session[:user_id] = @user.id
    redirect_to '/welcome'
  end

  def show
    @user = User.find(params[:id])
    @is_viewer_user = @user.username == current_user.username
    @host_events = Event.find_all_host_events(@user.username)
    @host_events = [] if @host_events.nil? or @host_events.empty?
    @join_events = Event.find_all_join_events(@user.username)
    @join_events = [] if @join_events.nil? or @join_events.empty?
  end

  def myProfile
    @username = current_user.username
    redirect_to user_path(current_user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if (!user_params["email"].blank?) and (user_params["email"] !~ URI::MailTo::EMAIL_REGEXP)
      flash[:warning] = "Email must be correctly filled in."
      redirect_to edit_user_path(@user)
    else
      @user.update_attributes!(user_params)
      flash[:notice] = "User '#{@user.username}' was successfully updated."
      redirect_to user_path(@user)
    end
  end
  
  def rateUser
    # host rates all attendee && attendee rate one host
    event = Event.find(params[:id])
    u = current_user.username
    is_viewer_host = event.host == u
    if !is_viewer_host
      user =  User.find_by(username: event.host)
      update_user_rating(user, params[event.host])
    else
      event.people.each do |u|
        user =  User.find_by(username: u)
        update_user_rating(user, params[u])
      end
    end
    event.update_attribute(:rated_users, event.rated_users.push(u))
    flash[:notice] = is_viewer_host ?  "You've rated attendees!" : "You've rated your host!"
    redirect_to '/events/'+params[:id]
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :email, :show_email, :show_my_events)
  end
  private
  def update_user_rating(u, new_r)
    # update user rating, given new rating
    # if new_r.nil? return
    old_r = u.rating
    cnt = u.num_rating_got
    u.update_attribute(:rating, ((old_r * cnt + new_r.to_i)/(cnt+1)).floor)
    u.update_attribute(:num_rating_got, cnt + 1)
  end
  private
  def cannot_create_user?(user_params)
    user_params[:username].nil? or user_params[:username].blank? or user_params[:password].nil? or user_params[:password].blank?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<!--  This file is app/views/users/edit.html.erb -->
<h2>Edit User</h2>

<%= form_tag user_path(@user), :method => :put do %>
  <div class="row">
    <div class="col-md-6">
      <%= label :user, :email, 'Email', :class => 'col-form-label' %>
      <%= text_field :user, :email, :class => 'form-control' %>
      <br>
      <div class="form-check form-switch">
        <label class="form-check-label" for="user_show_email">Make Email Public to Others</label>
        <input id="user_show_email_hidden" name="user[show_email]" type="hidden" value="false" class="form-check-input" />
        <% if @user.show_email %>
          <input id="user_show_email" name="user[show_email]" type="checkbox" class="form-check-input" role="switch" checked />
        <% else %>
          <input id="user_show_email" name="user[show_email]" type="checkbox" class="form-check-input" role="switch" />
        <% end %>
      </div>
      <br>
      <div class="form-check form-switch">
        <label class="form-check-label" for="user_show_my_events">Make My Hosted/Joined Events Public to Others</label>
        <input id="user_show_my_events_hidden" name="user[show_my_events]" type="hidden" value="false" class="form-check-input" />
        <% if @user.show_my_events %>
          <input id="user_show_my_events" name="user[show_my_events]" type="checkbox" class="form-check-input" role="switch" checked />
        <% else %>
          <input id="user_show_my_events" name="user[show_my_events]" type="checkbox" class="form-check-input" role="switch" />
        <% end %>
      </div>
    </div>
  </div>
  <br>
  <%= submit_tag 'Update User Profile', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', user_path(@user), :class => 'btn btn-secondary' %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit :class=>"btn btn-primary" %>
<%end%>

app/views/users/show.html.erb
<!--  This file is app/views/users/show.html.erb -->
<h2>Details about <em><%= @user.username %></em></h2>

<ul id="details">
  <li>
    🗣&nbsp;<b>Username</b>
    &nbsp;<%= @user.username %>
  </li>
  <li>
    📧&nbsp;<b>Email</b>
    <% if @user.show_email or @is_viewer_user %>
      &nbsp;<%= @user.email %>
    <% else %>
      &nbsp;set private by user 🔒
    <% end %>
  </li>
  <li>
    ✏️&nbsp;<b>Host Rating</b>
    &nbsp;
    <% @user.rating.times do %>
      ⭐️
    <% end %>
  </li>
  <li>
    📅&nbsp;<b>Join WeMeet Since</b>
    &nbsp;<%= @user.created_at.strftime("%m-%d-%Y") %>
  </li>
  <li>
    💰&nbsp;<b>Coins</b>
    &nbsp;<%= @user.coins %>
  </li>
</ul>
<br>

<div class="row">
  <% if @is_viewer_user %>
    <%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-outline-primary col-2' %>
  <% end %>
  <%= link_to 'Back to event list', events_path, :class => 'btn btn-outline-primary col-2' %>
</div>
<br>

<br>
<h3 class="details_padding">🎉<%= @user.username %>'s Events </h3>
<div class="container-fluid">
  <div class="row">

    <% if @user.show_my_events or @is_viewer_user %>
      <br>
      <div class="col-md-6">
        <h4>Hosted👑</h4>
    <% if @host_events.empty? %>
            <em><%= @user.username %></em> hasn't hosted any event
                <% if @is_viewer_user %>
                  <%= link_to "HOST NOW🤗", new_event_path() %>
                <% end %>
          <% else %>
        <table class="table table-striped col-md-12" id="events">
          <thead>
          <tr>
            <th>Title</th>
            <th>Status</th>
            <th>Details</th>
            <th>Rate</th>
          </tr>
          </thead>
          <tbody>
          
            <% @host_events.each do |event| %>
              <tr>
                <td>
                  <%= event.title %>
                </td>
                <td>
                 <% if event.status == 'open' %>
          
                  <span class="badge bg-success"><%= event.status %></span>
                  <% else  %>
                  <span class="badge bg-secondary"><%= event.status %></span>
                  <% end  %>
                </td>
                <td>
                  <%= link_to "Details", event_path(event), :class => 'btn btn-outline-secondary'%>
                </td>
                <td>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
          <% end %>
      </div>

      <div class="col-md-6">
      <h4>Joined🙌</h4>
      <% if @join_events.empty? %>
              <em><%= @user.username %></em> hasn't joined any event.
                <% if @is_viewer_user %>
                  <%= link_to "JOIN NOW👋", events_path %>
                <% end %>
          <% else %>
        <table class="table table-striped col-md-12" id="events">
          <thead>
          <tr>
            <th>Title</th>
            <th>Status</th>
            <th>Details</th>
            <th>Rate</th>
          </tr>
          </thead>
          <tbody>
          
            <% @join_events.each do |event| %>
              <tr>
                <td>
                  <%= event.title %>
                </td>
                <td>
                  <% if event.status == 'open' %>
          
          <span class="badge bg-success"><%= event.status %></span>
          <% else  %>
          <span class="badge bg-secondary"><%= event.status %></span>
          <% end  %>
                </td>
                <td>
                  <%= link_to "Details", event_path(event), :class => 'btn btn-outline-secondary'%>
                </td>
                <td>
                  <!-- <%= link_to "Rate", event_path(event), :class => 'btn btn-primary'%>-->
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% end %> 
      </div>
    <% else %>
      &nbsp;set private by user 🔒
    <% end %>
  </div>
</div>