config/routes.rb
Rottenpotatoes::Application.routes.draw do
  resources :users do
  end

  match '/myProfile', to: 'users#myProfile', as: 'myProfile', via: :get

  get 'login', to: 'sessions#new', as: 'sign_up'
  post 'login', to: 'sessions#create', as: 'log_in'
  get 'welcome', to: 'sessions#welcome', as: "login_signup"
  get 'authorized', to: 'sessions#page_requires_login'
  get 'logout', to: 'sessions#logout', as: 'logout'

  resources :events do
    resources :comments
  end 
  
  # map '/' to be a redirect to '/events'
  root :to => redirect('/welcome')

  match '/search_result', to: 'events#index', as: 'search_result', via: :get
  match '/join', to: 'events#join', as: 'join', via: :get
  match '/events/:id/promote', to: 'events#promote', as: 'promote', via: :get
  match '/events/:id/ratePeople', to: 'events#ratePeople', as: 'rate', via: :get
  match '/events/:id/rateUser', to: 'users#rateUser', as: 'rate_user', via: :put

  match '/events/:event_id/comments/:id/react/:action_id', to: 'comments#react', as: 'react', via: :put

  get '/auth/:provider/callback' => 'sessions#omniauth', as: 'oauth'
end

app/models/event.rb
class Event < ActiveRecord::Base
    enum status: [:open, :closed]
    has_many :comments, :dependent => :destroy
    has_and_belongs_to_many :users
    serialize :people, Array
    serialize :rated_users, Array
    after_initialize :init_event
    default_scope {order(promoted?: :DESC, event_time: :ASC)}

    def promotion_banner_style
        return 'table-success' if self.promoted?
        return ''
    end
    def self.find_all_host_events(username)
        Event.where(:host => username)
    end
    def self.find_all_join_events(username)
        Event.select { |event| event.people.include?("#{username}") }
    end
    def self.find_event_by_name(name)
        Event.where("title ILIKE ? OR host ILIKE ? OR people ILIKE ?", "%#{name}%", "%#{name}%", "%#{name}%")
    end

    def self.find_event_by_date(year, month)
        if !year.empty? && !month.empty?
            return Event.where("date_part('year',event_time) = ?", year).where("date_part('month',event_time) = ?", month)
        elsif year.empty? && month.empty?
            return nil
        elsif year.empty?
            return Event.where("date_part('month',event_time) = ?", "#{month}")
        else
            return Event.where("date_part('year',event_time) = ?", "#{year}")
        end
    end

    def self.find_event_by_category(category)
        if category == "Category"
            return nil
        else
            return Event.where("category = ?", "#{category}")
        end
    end

    def self.find_event_by_location(location)
        if location == "Location"
            return nil
        else
            return Event.where("location = ?", "#{location}")
        end
    end

    def self.find_event_by_status(status)
        if status == "Status"
            return nil
        elsif status == "Open"
            Event.where("status = 0")
        else
            Event.where("status = 1")
        end
    end

    # INTERNAL
    private 
    def init_event
        @people = []
        @rated_users = []
        @status = :open
        @attendee_limit = 10 #TODO refactor
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def show
      id = params[:id] # retrieve event ID from URI route
      u = current_user.username
      @event = Event.find(id) # look up event by unique ID
      @host = User.find_by(username: @event.host)
      @is_user_joined = @event.people.include?(u)
      @join_text = @is_user_joined ? :Unjoin : :Join
      @join_btn_style = get_join_button_style(u)
      @promote_btn_style = get_promote_btn_style(@event)
      @is_viewer_host = @event.host == u
      @username = u
      @rate_btn_style = get_rate_button_style(u)
      @attendees = {}
      @event.people.each do |person|
        @attendees[person] = User.find_by(username: person)
      end
      @user_id = User.find_by(username: u).id
      @usernames = User.pluck(:username)
    end
  
    def index
      # TODO: record user during login
      # session[:username] = 'testuser'

      #check for search query string
      q = params[:q].to_s.strip
      
      if not q.blank?
        # TODO issue #70
        event1 = Event.find_event_by_date(params[:select][:year], params[:select][:month])
        event2 = Event.find_event_by_category(params[:category_selected])
        event3 = Event.find_event_by_location(params[:location_selected])
        event4 = Event.find_event_by_status(params[:status_selected])
        event5 = Event.find_event_by_name(q)
        @events = [ event1, event2, event3, event4, event5 ].reject( &:nil? ).reduce( :& )
        @users = {}
        @events.each do |event|
          u = User.find_by(username: event.host)
          @users[event.host] = u
        end
        @page_name = "Search Result for '#{q}'"
      else
        @events = Event.all
        @users = {}
        @events.each do |event|
          u = User.find_by(username: event.host)
          @users[event.host] = u
        end
        @page_name = "Home"
      end
    end
  
    def new
      # default: render 'new' template
    end

    def create
      user = current_user.username
      check_result = is_event_params_valid(event_params)
      if check_result[:is_valid]
        @event = Event.create!(event_params)
        init_attributes = {:host => user, :joined => '0', :status => 0, :people => []}
        @event.update_attributes!(init_attributes)
        flash[:notice] = "Event '#{@event.title}' was successfully created."
        redirect_to events_path
      else
        flash[:warning] = "Field '#{check_result[:invalid_field]}' must be correctly filled in."
        # temporarily redirect to a new post event page
        redirect_to new_event_path
      end
    end

    def edit
      puts params
      @event = Event.find(params[:id])
    end

    def join
      u = current_user.username
      @event = Event.find(params[:id])
      is_unjoin = @event.people.include?(u)
      atts = @event.attributes
      atts[:people] = is_unjoin ? @event.people - [u] : @event.people.append(u)
      atts[:joined] = atts[:people].size
      @event.update_attributes!(atts)
      @join_btn_style = get_join_button_style(u)
      flash[:notice] = is_unjoin ? "You've unjoined it." : "You've joined it!"
      redirect_to event_path(@event)
    end

    def update
      @event = Event.find(params[:id])
      check_result = is_event_params_valid(event_params)
      if check_result[:is_valid]
        @event.update_attributes!(event_params)
        flash[:notice] = "Event '#{@event.title}' was successfully updated."
        redirect_to event_path(@event)
      else
        flash[:warning] = "Field '#{check_result[:invalid_field]}' must be correctly filled in."
        redirect_to edit_event_path(@event)
      end
    end

    def promote
      @event = Event.find(params[:id])
      host = User.find_by(username: @event.host)
      if host.promote_event
        @event.update_attribute(:promoted?, true)
        flash[:notice]='promoted!'
        redirect_to event_path(@event) and return
      end
      flash[:warning]='You don\'t have enough coins!'
      redirect_to event_path(@event)
    end

    def destroy
      @event = Event.find(params[:id])
      @event.destroy
      flash[:notice] = "Event '#{@event.title}' was deleted."
      redirect_to events_path
    end

    def ratePeople
      @event = Event.find(params[:id])
      u = current_user.username
      # @can_user_rate = !@event.rated_users.include?(u)
      @rate_btn_style = get_rate_button_style(u)
      puts "btn style"
      puts @rate_btn_style
      @is_viewer_host = @event.host == u
    end

    private
    def event_params
      params.require(:event).permit(:title, :host, :joined, :people, :status, :event_time, :attendee_limit, :description, :q, :category, :location)
    end

    private
    def is_event_params_valid(params)
      result = {:is_valid => true, :invalid_field => 'None'}
      # date = Date.strptime(params['event_time(1i)'] + '-' + params['event_time(2i)'] + '-' + params['event_time(3i)'],"%Y-%m-%d")
      if params["title"].nil? or params["title"].blank?
        result[:is_valid] = false
        result[:invalid_field] = 'Title'
      elsif params["attendee_limit"].nil? or params["attendee_limit"].blank?
        result[:is_valid] = false
        result[:invalid_field] = 'Maximum Number of Attendees'
      elsif Date.parse(params['event_time(1i)'] + '-' + params['event_time(2i)'] + '-' + params['event_time(3i)']).past?
        result[:is_valid] = false
        result[:invalid_field] = 'Event Time'
      end
      puts params[:event_time]
      return result
    end

    private
    def get_join_button_style(uname)
      return 'btn btn-secondary col-2' if @event.people.include?(uname)
      return 'btn btn-success col-2 disabled' if @event.people.size >= @event.attendee_limit or @event.status == "closed"
      return 'btn btn-success col-2'
    end
    def get_rate_button_style(u)
      return 'btn btn-outline-primary col-2 disabled' if @event.rated_users.include?(u)
      return 'btn btn-outline-primary col-2'
    end
    def get_promote_btn_style(e)
      return 'btn btn-outline-secondary col-2 disabled' if e.promoted?
      return 'btn btn-outline-info col-2'
    end
  end
  

app/views/events/edit.html.erb
<!--  This file is app/views/events/edit.html.erb -->
<h2>Edit Event</h2>

<%= form_tag event_path(@event), :method => :put do %>
  <div class="row">
    <div class="col-md-6">
      <%= label :event, :title, 'Title', :class => 'col-form-label' %>
      <%= text_field :event, :title, :class => 'form-control' %>
      <br>
      <%= label :event, :event_time, 'Event Time', :class => 'col-form-label'  %>
      <%= date_select :event, :event_time, {}, :class => 'form-control col-2 d-inline' %>
      <br>
      <%= label :event, :attendee_limit, 'Maximum Number of Attendees', :class => 'col-form-label'  %>
      <%= text_field :event, :attendee_limit, :class => 'form-control' %>
      <%= label :event, :description, 'Event Description', :class => 'col-form-label'  %>
      <%= text_field :event, :description, :class => 'form-control' %>
      <%= label :event, :status, 'Status', :class => 'col-form-label'  %>
      <%= select :event, :status, [:open, :closed], {}, {:class => 'form-control col-1'} %>
      <%= label :event, :category, 'Category', :class => 'col-form-label'  %>
      <%= select :event, :category, [ "Food","Entertainment","Sports","Academic","Other"], {}, {:class => 'form-control col-1'} %>
      <br>
      <%= label :event, :location, 'Event Location', :class => 'col-form-label' %>
      <%= select :event, :location, ['Butler Library', 'Lerner Hall', 'John Jay', 'Dodge', 'Low Library', 'Uris', 'Mudd', 'Northwest Corner Building', 'International Affairs', 'Kent', 'Philosophy', 'Hamilton', 'Pulitzer', 'Mathematics', 'Avery', 'Fayerweather', 'Schermerhorn', 'Chandler', 'Pupin', 'Schapiro CEPSR', 'Faculty House', 'Barnard', 'Law School', 'Wallach', 'Hartley', 'Wien', 'East Campus', 'Other Off Campus Place'], {}, {:class => 'form-control col-1'} %>
    </div>
  </div>
  <br/>
  <%= submit_tag 'Update Event Info', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', event_path(@event), :class => 'btn btn-secondary' %>
<% end %>

app/views/events/index.html.erb
<!--  This file is app/views/events/index.html.erb -->
<h1><%= @page_name %></h1>

<hr>
<div>
<%= form_tag search_result_path, method: :get, id: 'search_form' do %>
    <%= text_field_tag :q, nil, :required => true, size: 50, placeholder: "Search event/host/attendee name" %> 
    <%= submit_tag "Search", class: "btn btn-primary", id: "search_result" %>
    
    <div> Available Events in: 
    <%= select_year(0, {:prompt => "Year", :start_year => DateTime.now.year,:end_year => DateTime.now.year - 5, prefix: 'select'},{:field_name => 'year', :id => 'start-year'}) %>
    <%= select_month(0, {:prompt => "Month", prefix: 'select'},{:field_name => 'month', :id => 'start-month'}) %>
    </div>

    <div> Events Category: 
    <%= select_tag "category_selected", options_for_select([ "Category","Food","Entertainment","Sports","Academic","Other"], "Category") %>
    </div>

    <div> Events Location:
      <%= select_tag "location_selected", options_for_select(['Location', 'Butler Library', 'Lerner Hall', 'John Jay', 'Dodge', 'Low Library', 'Uris', 'Mudd', 'Northwest Corner Building', 'International Affairs', 'Kent', 'Philosophy', 'Hamilton', 'Pulitzer', 'Mathematics', 'Avery', 'Fayerweather', 'Schermerhorn', 'Chandler', 'Pupin', 'Schapiro CEPSR', 'Faculty House', 'Barnard', 'Law School', 'Wallach', 'Hartley', 'Wien', 'East Campus', 'Other Off Campus Place'], "Location") %>
    </div>

    <div> Status of the event:
    <%= select_tag "status_selected", options_for_select(["Status","Open","Closed"], "Status") %>
    </div>
<% end %>
</div>
<hr>

<%#  Part 2: Start here... %>

<table class="table table-striped col-md-12" id="events">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Host</th>
      <th>Host Rating</th>
      <th>Time</th>
      <th>Status</th>
      <th>Joined</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
    <% if event.promoted?  %>
      <tr class="table-danger border border-danger border-4">
    <% else  %>
      <tr class="">
    <% end  %>
        <td>
          <% if event.promoted?  %>
            <%= link_to event.title, event_path(event), :class=>""%>
          <% else  %>
            <%= link_to event.title, event_path(event)%>
          <% end  %>
        </td>
        <td>
        <%= event.category %>
        </td>
        <td>
          <%= link_to event.host, user_path(@users.fetch(event.host)) %>
        </td>
        <td>
          <% (@users.fetch(event.host).rating.nil? ? 5 : @users.fetch(event.host).rating).times do %>
            ⭐️
          <% end %>
        </td>
        <td>
          <%= event.event_time.nil? ? "TBD" : event.event_time.strftime("%m-%d-%Y") %>
        </td>
        <td>
          <% if event.status == 'open' %>
          
          <span class="badge bg-success"><%= event.status %></span>
          <% else  %>
          <span class="badge bg-secondary"><%= event.status %></span>
          <% end  %>
        </td>
        <td>
          <%= event.joined %>
        </td>
        <td>
          <%= link_to "Details", event_path(event), :class => 'btn btn-outline-secondary'%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<!--  This file is app/views/events/new.html.erb -->
<h2>Post New Event</h2>
<div class='col-8'>
<%= form_tag events_path, :class => 'form' do %>
  <div class="row">
    <div class="col-md-6">
      <%= label :event, :title, 'Title', :class => 'col-form-label' %>
      <%= text_field :event, :title, :class => 'form-control' %>
      <br>
      <%= label :event, :event_time, 'Event Time', :class => 'col-form-label'  %>
      <%= date_select :event, :event_time, {}, :class => 'form-control col-2 d-inline' %>
      <br>
      <%= label :event, :attendee_limit, 'Maximum Number of Attendees', :class => 'col-form-label'  %>
      <%= text_field :event, :attendee_limit, :class => 'form-control' %>
      <%= label :event, :description, 'Event Description', :class => 'col-form-label'  %>
      <%= text_field :event, :description, :class => 'form-control' %>
      <%= label :event, :category, 'Event Category', :class => 'col-form-label' %>
      <br>
      <%= select :event, :category, [ "Food","Entertainment","Sports","Academic","Other"], {}, {:class => 'form-control col-1'} %>
      <br>
      <%= label :event, :location, 'Event Location', :class => 'col-form-label' %>
      <%= select :event, :location, ['Butler Library', 'Lerner Hall', 'John Jay', 'Dodge', 'Low Library', 'Uris', 'Mudd', 'Northwest Corner Building', 'International Affairs', 'Kent', 'Philosophy', 'Hamilton', 'Pulitzer', 'Mathematics', 'Avery', 'Fayerweather', 'Schermerhorn', 'Chandler', 'Pupin', 'Schapiro CEPSR', 'Faculty House', 'Barnard', 'Law School', 'Wallach', 'Hartley', 'Wien', 'East Campus', 'Other Off Campus Place'], {}, {:class => 'form-control col-1'} %>
    </div>
  </div>
  <br/>
  <%= submit_tag 'Post Event', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', events_path, :class => 'btn btn-outline-secondary' %>
<% end %>
</div>

app/views/events/ratePeople.html.erb
<%= form_tag rate_user_path(@event), method: :put, id: 'rate_form' do %>
    <% if @is_viewer_host %>
        <% @event.people.each do |person| %>
            <div>
            <%= person %>&nbsp;&nbsp;&nbsp;
            <%= select_tag "#{person}", options_for_select([5,4,3,2,1], 5) %>
            </div>
        <% end %>

        <div>
            <%= submit_tag "Submit", class: "btn btn-primary", id: "rate_submit" %>
        </div>
    <% else %>
        <div>
        <%= @event.host %>&nbsp;&nbsp;&nbsp;
        <%= select_tag "#{ @event.host}", options_for_select([5,4,3,2,1], 5) %>
        </div>

        <div>
        <%= submit_tag "Submit", class: "btn btn-primary", id: "rate_submit" %>
        </div>
    <% end %>

<% end %>

app/views/events/show.html.erb
<!--  This file is app/views/events/show.html.erb -->
<h2>Details about <em><%= @event.title %></em></h2>
<div class='row'>
<div class='col-6'>
<ul id="details">
  <li>
    🗣&nbsp;<b>Host</b>
    &nbsp;<%= link_to @event.host, user_path(@host) %>
  </li>
  <li>
    ✏️&nbsp;<b>Host Rating</b>
    &nbsp;
    <% (@host.rating.nil? ? 5 : @host.rating).times do %>
      ⭐️
    <% end %>
  </li>
  <li>
    📅&nbsp;<b>Event Time</b>
    &nbsp;<%= @event.event_time.nil? ? "TBD" : @event.event_time.strftime("%m-%d-%Y") %>
  </li>
  <li>
    📍&nbsp;<b>Event Location</b>
    &nbsp;<%= @event.location.nil? ? "TBD" : @event.location %>
  </li>
  <li>
    ⏳&nbsp;<b>Event Status</b>
     <% if @event.status == 'open' %>
          &nbsp;<span class="badge bg-success"><%= @event.status %></span>
          <% else  %>
          &nbsp;<span class="badge bg-secondary"><%= @event.status %></span>
          <% end  %>
  </li>
  <li>
    🏓&nbsp;<b>Event Category</b>
    &nbsp;<%= @event.category %>
  </li>
  <li>
    🧐&nbsp;<b>Maximum Number of Attendees</b>
    &nbsp;<%= @event.attendee_limit %>
  </li>
  <li>
    <% if @event.people.length < 6 %>
      👥&nbsp;<b>Attending People</b>
      &nbsp;
      <% @event.people.each do |person| %>
        <%= link_to person, user_path(@attendees.fetch(person)) %>&nbsp;&nbsp;&nbsp;
      <% end %>
    <% else %>
      👥&nbsp;<b>Attending People</b>
      <details>
        <summary>Click to view all attendees</summary>
        <% @event.people.each do |person| %>
          <%= link_to person, user_path(@attendees.fetch(person)) %>&nbsp;&nbsp;&nbsp;
        <% end %>
      </details>
    <% end %>
  </li>
</ul>

<h3>Description:</h3>
<p id="description">
  <div class='card card-body'>
  <%= @event.description %>
  </div>
</p>
</div>
<div class='col-6'>
  <%# <img src="https://picsum.photos/200/300" class="rounded mx-auto d-block"> %>
</div>
</div>
<br>

<div class="row">
  <% if @is_viewer_host %>
    <%= link_to 'Edit', edit_event_path(@event), :class => 'btn btn-outline-primary col-2' %>
    <%= link_to 'Delete', event_path(@event), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-outline-danger col-2' %>
    <%= link_to 'Promote', promote_path(@event), :class => @promote_btn_style %>
    
    <% if @event.status == "closed" %>
      <%= link_to 'Rate your attendees', rate_path(@event, @is_viewer_host), :class => @rate_btn_style %>
    <% end %>

  <% end %>
  <%= link_to 'Back to event list', events_path, :class => 'btn btn-outline-primary col-2' %>
  <%# Join: if user is not host && there's space %>
  <% if !@is_viewer_host %>
  <%= link_to @join_text, join_path({:id=>@event.id}), :class => @join_btn_style, :id => 'join_btn'%>
  
    <% if @event.status == "closed" && @is_user_joined %>
        <%= link_to 'Rate your host', rate_path(@event, @is_viewer_host), :class => @rate_btn_style %>
    <% end %>

  <% end %>
</div>
<br>

<br>
<h3 class="details_padding">📒Comments </h3>
<%# <p>
  <a class="btn btn-outline-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Comments
  </a>
</p> %>
<%# <div class="collapse" id="collapseExample">
  <div class="card card-body"> %>

<table class="table col-md-12 borderless" id="comments">
  <thead class="bottom">
    <tr>
      <th>👤User</th>
      <th>🖊️Comment</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @event.comments.each do |comment| %>
      <tr>
        <td class='col-md-2'>
          <%= link_to comment.user.username, user_path(comment.user.id) %>&nbsp;&nbsp;&nbsp;
        </td>
        <td class='col-md-6'>
        <div class='lead'>
          <%= comment.content %>
          </div>
        </td>
        <td class='col-md-2'>
          <% if comment.user.username == @username %>
            <%= link_to 'Edit', edit_event_comment_path(@event, comment.id), :class => 'btn btn-outline-secondary col-4' %>
            <%= link_to 'Delete', event_comment_path(@event, comment.id), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-outline-danger col-4' %>
          <% end %>
        </td>
      </tr>
      <tr class="bottom">
        <td class='col-md-2'>
          <div class="row">
            <% if comment.reactions.is_reacted(comment.id, @user_id) %>
              <% if comment.reactions.is_thumbuped(comment.id, @user_id) %>
                <div class="col-md-2">
                  <%= button_to '', react_path(@event, comment.id, 0), :method => :put, :id => 'thumbup' %>
                </div>
              <% end %>
              <% if comment.reactions.is_liked(comment.id, @user_id) %>
                <div class="col-md-2">
                  <%= button_to '', react_path(@event, comment.id, 1), :method => :put, :id => "like" %>
                </div>
              <% end %>
              <% if comment.reactions.is_laughed(comment.id, @user_id) %>
                <div class="col-md-2">
                  <%= button_to '', react_path(@event, comment.id, 2), :method => :put, :id => "laugh" %>
                </div>
              <% end %>
            <% else %>
              <div class="col-md-2">
                <%= button_to '', react_path(@event, comment.id, 0), :method => :put, :id => 'thumbup' %>
              </div>
              <div class="col-md-2">
                <%= button_to '', react_path(@event, comment.id, 1), :method => :put, :id => "like" %>
              </div>
              <div class="col-md-2">
                <%= button_to '', react_path(@event, comment.id, 2), :method => :put, :id => "laugh" %>
              </div>
            <% end %>
          </div>
        </td>
        <% if comment.reactions.count_reacts(comment.id)>0 %>
          <td class='col-md-6'>
          <p><small>
            <% comment.reactions.find_people(comment.id).each do |name| %>
              <%= name + ", " %>
            <% end %>
            <span>and others</span>
          </small></p>
          </td>
          <td class='col-md-2'>
            <%= comment.reactions.count_reacts(comment.id) %>
            <span> Reactions</span>
          </td>
        <% else %>
          <td class='col-md-8'>
            <span>👈 Be the first one to react</span>
          </td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_tag event_comments_path(@event), :class => 'form' do %>
  <%= label :comment, '', :class => 'col-form-label' %>
  <%= text_field :comment, :content, :class => 'form-control', placeholder: 'Leave a quick comment (length limit: 100)', maxlength: 100 %>
  <br>
  <%= submit_tag 'Post Comment', :class => 'btn btn-primary' %>
<% end %>
  <%# </div>
</div> %>

<script> 
  data = <%= raw @usernames.compact.to_json %>;
  $('#comment_content').atwho({at:"@", 'data':data}); 
</script>