config/routes.rb
Rottenpotatoes::Application.routes.draw do
  resources :users do
  end

  match '/myProfile', to: 'users#myProfile', as: 'myProfile', via: :get

  get 'login', to: 'sessions#new', as: 'sign_up'
  post 'login', to: 'sessions#create', as: 'log_in'
  get 'welcome', to: 'sessions#welcome', as: "login_signup"
  get 'authorized', to: 'sessions#page_requires_login'
  get 'logout', to: 'sessions#logout', as: 'logout'

  resources :events do
    resources :comments
  end 
  
  # map '/' to be a redirect to '/events'
  root :to => redirect('/welcome')

  match '/search_result', to: 'events#index', as: 'search_result', via: :get
  match '/join', to: 'events#join', as: 'join', via: :get
  match '/events/:id/promote', to: 'events#promote', as: 'promote', via: :get
  match '/events/:id/ratePeople', to: 'events#ratePeople', as: 'rate', via: :get
  match '/events/:id/rateUser', to: 'users#rateUser', as: 'rate_user', via: :put

  match '/events/:event_id/comments/:id/react/:action_id', to: 'comments#react', as: 'react', via: :put

  get '/auth/:provider/callback' => 'sessions#omniauth', as: 'oauth'
end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
  <head>
    <title>WeMeet</title>
    <%# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> %>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>
  <body>
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <h2 class="title">WeMeet!</h2>
      <ul class="navbar-nav mr-auto">
          <li class='nav-item'>
            <%= link_to "Home", events_path, :class => 'nav-link'%>
          </li>
          <li>
            <%= link_to "Post Event", new_event_path, :class => 'nav-link' %>
          </li>
          <li>
            <%= link_to "My Profile", myProfile_path(@username), :class => 'nav-link' %>
          </li>
          <li>
            <% if logged_in? %>
              <%= link_to  "Logout " + current_user.username, logout_path, :class => 'btn btn-outline-secondary' %>
            <%else%>
              <%= link_to "Login/Signup", login_signup_path, :class => 'nav-link' %>
            <%end%>
          </li>
      </ul>
    </nav>
    <div class="container">
    <%# Render "flash" messages in our application. This loads _flash.erb %>
    <%= render 'layouts/flash' %>
    <main id="main">
      <%= yield %>
    </main>
  </div>
</body>
</html>